### ISSUE TITLE
Feature to disable run start on death or pause menu

### ISSUE THREAD

**Issue by AJ213** [Happyrobot33/Autosplitters#17]
As title states, add options to allow autosplitter to not start on player death or on restart in the in-game pause menu.

**Comment by Happyrobot33** [comment]
Need clarification with the current commits to be considered an issue

**Comment by AJ213** [comment]
What this post basically means is a setting to prevent the autosplitter from starting while the player is in the game. I made a pull request for the solution to this and you can edit it to make it cleaner if you want.

**Comment by Happyrobot33** [comment]
added in commit [#74](https://github.com/Happyrobot33/Autosplitters/commit/28a65947d09e392fff8ae68e54ac82bf79aa4863)
