### ISSUE TITLE
Reloading Level Unpauses IGT Too Early

### ISSUE THREAD

**Issue by AJ213** [Happyrobot33/Autosplitters#25]
**Describe the bug**
When the player buffers a restart before they enter a level, the timer likely gets initialized making the autosplitter believe that the player is currently in the level (when they are not). Meaning, the autosplitter is detecting the player to be out of the level complete screen when they are not.

**To Reproduce**
1. Start Recording
2. Open Clustertruck
3. Start a run with the autosplitter going
4. Hit the R key after hitting the next level button in the level complete screen.
4a. if you want to visually see the issue, spam R after hitting the next level button.
4b. The result should be that the IGT will unpause incorrectly according to the IGT timing standard.
5. Double check recording to see if IGT is unpaused when you hit R

**Expected behavior**
IGT should not be running while the player is inside the level complete screen according to the timing standards.

The current IGT standard is that the run starts on the first frame of the visible level and pauses on the first visible frame of the level complete screen. When the first frame of the next level is visible, unpause for IGT.

**Video Examples**
You will need to go frame by frame to see the issue.
https://youtu.be/CjK-eEsVjLU?t=35
https://youtu.be/YT-J_bnG_ek?t=21
https://youtu.be/cL30nU-q40s?t=1257

**Desktop (please complete the following information):**
This issue is universal, but does happen to me too so here is my info:
OS: Windows 10
Processor: AMD Ryzen 5 2600X Six-Core Processor
Setttings: Nothing enabled by start and split

**Additional context**
Although this issue doesn't seem significant, this has led to some ILs being a second slower than expected and the full game runs being slower by a few seconds. If this is not fixed, the autosplitter can not be trusted to be used for IGT alone.

**Comment by Happyrobot33** [comment]
there is now a _bounty_ for a fix to this bug. **50$**. check the ClusterTruck speedrunning discord for more info

**Comment by AJ213** [comment]
Fixed in #26
