### ISSUE TITLE
Timer Starts Incorrectly Compared To Current Rules

### ISSUE THREAD

**Issue by AJ213** [Happyrobot33/Autosplitters#6]
Current speedrun.com rules have the timer start on the first frame of the first level. This autosplitter starts when the start button is pressed instead. Not a huge issue since the difference is 500ms at most, but still an issue regardless.

**Comment by Happyrobot33** [comment]
thought this was fixed with https://github.com/Happyrobot33/Autosplitters/commit/a956ba7cc0f5cadea9f67b5fe1da52daea3cdd22

**Comment by Happyrobot33** [comment]
currently ~170ms off, need a new method

**Comment by Happyrobot33** [comment]
Fixed in https://github.com/Happyrobot33/Autosplitters/commit/8c2109b04cd5375776817348adb649cf70954bc0
