### ISSUE TITLE
Option For Timer End For Individual Worlds

### ISSUE THREAD

**Issue by AJ213** [Happyrobot33/Autosplitters#7]
The timer stops for IWs on the 10th or 5th level right as the level completion screen pops up. However, this autosplitter only splits once the player hits the next level button instead. This would mean that the player would have to manually split for worlds (especially halloween or holidays) or hit the next level button (which loses time).

**Comment by Happyrobot33** [comment]
esay fix, will do tommorow

**Comment by AJ213** [comment]
A valid way to approach this problem is to have an option for the autosplitter to split on level completion for all levels rather than split on next level button click. However, if you do this it would be preferred if you make an option for only the final level of the world (which is not always the 10th level btw, you may have to have another option just for holidays) to have this type of split. The only reason for this many options is because currently, the option mentioned earlier is how people's split files are set up and timed.

**Comment by Happyrobot33** [comment]
currently shelving as there is no way to detect the end of a level other than another level loading

**Comment by Happyrobot33** [comment]
Hackily Fixed when using IGT added in commit [#67](https://github.com/Happyrobot33/Autosplitters). still doesn't work outside of IGT
