### ISSUE TITLE
Autosplitter Splits or Restarts in The Menu

### ISSUE THREAD

**Issue by AJ213** [Happyrobot33/Autosplitters#8]
Autosplitter will reset or split in the level selection menu if you select a different level than the one you exited out of. If the player hovers over a level in advance the autosplitter will split the number of levels in advance (typically one, but possibly more if done on accident). Otherwise, if the level selected is behind the autosplitter will restart. If you fear this will mess with people switching abilities, it actually won't because hitting "exit to menu" will correctly cause a split. If this behavior is intended, it should be an option to enable/disable for people who don't want this functionality like me.

**Comment by Happyrobot33** [comment]
This behaviour is intended, and technically in the settings, but could be expanded on

**Comment by Happyrobot33** [comment]
Fixed by the introduction of dev mode, will only reset or keep your current level split, will not go ahead unless you are in dev mode.
